# title: Deep Image Spatial Transformation <br> for Person Image Generation
description: <a href="https://renyurui.github.io">Yurui Ren</a>, <a href="http://www.ece.pku.edu.cn/info/1012/1091.htm">Ge Li</a>, Yuanqi Chen, Thomas H. Li, Shan Liu <br> <a href="http://iccv2021.thecvf.com">ICCV 2021</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman