# title: Deep Image Spatial Transformation <br> for Person Image Generation
description: Yurui Ren, Ge Li, Yuanqi Chen, Thomas H. Li, Shan Liu <br> ICCV 2021
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman